// Generated by commsdsl2comms v5.2.0

/// @file
/// @brief Contains protocol version definition.

#pragma once

#include "comms/version.h"

/// @brief Version of the protocol specification.
#define CC_X509_SPEC_VERSION (0U)

/// @brief Major version of the protocol library.
#define CC_X509_MAJOR_VERSION (0)

/// @brief Minor version of the protocol library.
#define CC_X509_MINOR_VERSION (3)

/// @brief Patch version of the protocol library.
#define CC_X509_PATCH_VERSION (0)

/// @brief Full version of the protocol library as single number.
#define CC_X509_VERSION (COMMS_MAKE_VERSION(CC_X509_MAJOR_VERSION, CC_X509_MINOR_VERSION, CC_X509_PATCH_VERSION))

namespace cc_x509
{

/// @brief Version of the protocol specification.
inline constexpr unsigned specVersion()
{
    return CC_X509_SPEC_VERSION;
}

/// @brief Major version of the protocol library
inline constexpr unsigned versionMajor()
{
    return CC_X509_MAJOR_VERSION;
}

/// @brief Minor version of the protocol library
inline constexpr unsigned versionMinor()
{
    return CC_X509_MINOR_VERSION;
}

/// @brief Patch version of the protocol library
inline constexpr unsigned versionPatch()
{
    return CC_X509_PATCH_VERSION;
}

/// @brief Full version of the protocol library as a single number
inline constexpr unsigned version()
{
    return CC_X509_VERSION;
}

} // namespace cc_x509

// Generated compile time check for minimal supported version of the COMMS library
static_assert(COMMS_MAKE_VERSION(5, 0, 3) <= comms::version(),
    "The version of COMMS library is too old");
