// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains definition of <b>"Certificate"</b> field.

#pragma once

#include <cstdint>
#include <tuple>
#include "cc_x509/asn1/der/field/Length.h"
#include "cc_x509/asn1/der/field/RawBitString.h"
#include "cc_x509/field/AlgorithmIdentifier.h"
#include "cc_x509/field/CertificateCommon.h"
#include "cc_x509/field/FieldBase.h"
#include "cc_x509/field/TBSCertificate.h"
#include "cc_x509/options/DefaultOptions.h"
#include "comms/field/Bundle.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"

namespace cc_x509
{

namespace field
{

/// @brief Scope for all the member fields of
///     @ref Certificate field.
/// @tparam TOpt Protocol options.
template <typename TOpt = cc_x509::options::DefaultOptions>
struct CertificateMembers
{
    /// @brief Definition of <b>"Tag"</b> field.
    class Tag : public
        comms::field::IntValue<
            cc_x509::field::FieldBase<>,
            std::uint8_t,
            comms::option::def::FailOnInvalid<>,
            comms::option::def::DefaultNumValue<48>,
            comms::option::def::ValidNumValue<48>,
            comms::option::def::HasCustomRefresh
        >
    {
        using Base =
            comms::field::IntValue<
                cc_x509::field::FieldBase<>,
                std::uint8_t,
                comms::option::def::FailOnInvalid<>,
                comms::option::def::DefaultNumValue<48>,
                comms::option::def::ValidNumValue<48>,
                comms::option::def::HasCustomRefresh
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_x509::field::CertificateMembersCommon::TagCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_x509::field::CertificateMembersCommon::TagCommon::name();
        }

        /// @brief Generated refresh functionality.
        bool refresh()
        {
            bool updated = Base::refresh();
            if (Base::valid()) {
                return updated;
            };
            Base::setValue(48);
            return true;
        }
    };

    /// @brief Definition of <b>"Length"</b> field.
    using Length =
        cc_x509::asn1::der::field::Length<
            TOpt
        >;

    /// @brief Scope for all the member fields of
    ///     @ref Value field.
    struct ValueMembers
    {
        /// @brief Definition of <b>"tbsCertificate"</b> field.
        class TbsCertificate : public
            cc_x509::field::TBSCertificate<
                TOpt
            >
        {
            using Base =
                cc_x509::field::TBSCertificate<
                    TOpt
                >;
        public:
            /// @brief Name of the field.
            static const char* name()
            {
                return cc_x509::field::CertificateMembersCommon::ValueMembersCommon::TbsCertificateCommon::name();
            }
        };

        /// @brief Definition of <b>"signatureAlgorithm"</b> field.
        class SignatureAlgorithm : public
            cc_x509::field::AlgorithmIdentifier<
                TOpt
            >
        {
            using Base =
                cc_x509::field::AlgorithmIdentifier<
                    TOpt
                >;
        public:
            /// @brief Name of the field.
            static const char* name()
            {
                return cc_x509::field::CertificateMembersCommon::ValueMembersCommon::SignatureAlgorithmCommon::name();
            }
        };

        /// @brief Definition of <b>"signatureValue"</b> field.
        class SignatureValue : public
            cc_x509::asn1::der::field::RawBitString<
                TOpt
            >
        {
            using Base =
                cc_x509::asn1::der::field::RawBitString<
                    TOpt
                >;
        public:
            /// @brief Name of the field.
            static const char* name()
            {
                return cc_x509::field::CertificateMembersCommon::ValueMembersCommon::SignatureValueCommon::name();
            }
        };

        /// @brief All members bundled in @b std::tuple.
        using All =
            std::tuple<
               TbsCertificate,
               SignatureAlgorithm,
               SignatureValue
            >;
    };

    /// @brief Definition of <b>"Value"</b> field.
    class Value : public
        comms::field::Bundle<
            cc_x509::field::FieldBase<>,
            typename ValueMembers::All
        >
    {
        using Base =
            comms::field::Bundle<
                cc_x509::field::FieldBase<>,
                typename ValueMembers::All
            >;
    public:
        /// @brief Allow access to internal fields.
        /// @details See definition of @b COMMS_FIELD_MEMBERS_NAMES macro
        ///     related to @b comms::field::Bundle class from COMMS library
        ///     for details.
        ///
        ///     The generated values, types and access functions are:
        ///     @li @b FieldIdx_tbsCertificate index, @b Field_tbsCertificate type and @b field_tbsCertificate() access function -
        ///         for cc_x509::field::CertificateMembers::ValueMembers::TbsCertificate member field.
        ///     @li @b FieldIdx_signatureAlgorithm index, @b Field_signatureAlgorithm type and @b field_signatureAlgorithm() access function -
        ///         for cc_x509::field::CertificateMembers::ValueMembers::SignatureAlgorithm member field.
        ///     @li @b FieldIdx_signatureValue index, @b Field_signatureValue type and @b field_signatureValue() access function -
        ///         for cc_x509::field::CertificateMembers::ValueMembers::SignatureValue member field.
        COMMS_FIELD_MEMBERS_NAMES(
            tbsCertificate,
            signatureAlgorithm,
            signatureValue
        );

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_x509::field::CertificateMembersCommon::ValueCommon::name();
        }
    };

    /// @brief All members bundled in @b std::tuple.
    using All =
        std::tuple<
           Tag,
           Length,
           Value
        >;
};

/// @brief Definition of <b>"Certificate"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = cc_x509::options::DefaultOptions, typename... TExtraOpts>
class Certificate : public
    comms::field::Bundle<
        cc_x509::field::FieldBase<>,
        typename CertificateMembers<TOpt>::All,
        TExtraOpts...,
        comms::option::def::RemLengthMemberField<1U>
    >
{
    using Base =
        comms::field::Bundle<
            cc_x509::field::FieldBase<>,
            typename CertificateMembers<TOpt>::All,
            TExtraOpts...,
            comms::option::def::RemLengthMemberField<1U>
        >;
public:
    /// @brief Allow access to internal fields.
    /// @details See definition of @b COMMS_FIELD_MEMBERS_NAMES macro
    ///     related to @b comms::field::Bundle class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and access functions are:
    ///     @li @b FieldIdx_tag index, @b Field_tag type and @b field_tag() access function -
    ///         for cc_x509::field::CertificateMembers::Tag member field.
    ///     @li @b FieldIdx_length index, @b Field_length type and @b field_length() access function -
    ///         for cc_x509::field::CertificateMembers::Length member field.
    ///     @li @b FieldIdx_value index, @b Field_value type and @b field_value() access function -
    ///         for cc_x509::field::CertificateMembers::Value member field.
    COMMS_FIELD_MEMBERS_NAMES(
        tag,
        length,
        value
    );

    /// @brief Name of the field.
    static const char* name()
    {
        return cc_x509::field::CertificateCommon::name();
    }
};

} // namespace field

} // namespace cc_x509
