// Generated by commsdsl2comms v7.3.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_x509::field::Certificate field.

#pragma once

#include <cstdint>
#include "cc_x509/asn1/der/field/LengthCommon.h"
#include "cc_x509/asn1/der/field/RawBitStringCommon.h"
#include "cc_x509/field/AlgorithmIdentifierCommon.h"
#include "cc_x509/field/TBSCertificateCommon.h"

namespace cc_x509
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref cc_x509::field::Certificate field.
struct CertificateMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_x509::field::CertificateMembers::Tag field.
    struct TagCommon
    {
        /// @brief Re-definition of the value type used by
        ///     cc_x509::field::CertificateMembers::Tag field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref cc_x509::field::CertificateMembers::Tag field.
        static const char* name()
        {
            return "Tag";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref cc_x509::field::CertificateMembers::Length field.
    using LengthMembersCommon = cc_x509::asn1::der::field::LengthMembersCommon;

    /// @brief Common types and functions for
    ///     @ref cc_x509::field::CertificateMembers::Length field.
    using LengthCommon = cc_x509::asn1::der::field::LengthCommon;

    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref cc_x509::field::CertificateMembers::Value field.
    struct ValueMembersCommon
    {
        /// @brief Common definitions of the member fields of
        ///     @ref cc_x509::field::CertificateMembers::ValueMembers::TbsCertificate field.
        using TbsCertificateMembersCommon = cc_x509::field::TBSCertificateMembersCommon;

        /// @brief Common types and functions for
        ///     @ref cc_x509::field::CertificateMembers::ValueMembers::TbsCertificate field.
        struct TbsCertificateCommon : public cc_x509::field::TBSCertificateCommon
        {
            /// @brief Name of the @ref cc_x509::field::CertificateMembers::ValueMembers::TbsCertificate field.
            static const char* name()
            {
                return "tbsCertificate";
            }
        };

        /// @brief Common definitions of the member fields of
        ///     @ref cc_x509::field::CertificateMembers::ValueMembers::SignatureAlgorithm field.
        using SignatureAlgorithmMembersCommon = cc_x509::field::AlgorithmIdentifierMembersCommon;

        /// @brief Common types and functions for
        ///     @ref cc_x509::field::CertificateMembers::ValueMembers::SignatureAlgorithm field.
        struct SignatureAlgorithmCommon : public cc_x509::field::AlgorithmIdentifierCommon
        {
            /// @brief Name of the @ref cc_x509::field::CertificateMembers::ValueMembers::SignatureAlgorithm field.
            static const char* name()
            {
                return "signatureAlgorithm";
            }
        };

        /// @brief Common definitions of the member fields of
        ///     @ref cc_x509::field::CertificateMembers::ValueMembers::SignatureValue field.
        using SignatureValueMembersCommon = cc_x509::asn1::der::field::RawBitStringMembersCommon;

        /// @brief Common types and functions for
        ///     @ref cc_x509::field::CertificateMembers::ValueMembers::SignatureValue field.
        struct SignatureValueCommon : public cc_x509::asn1::der::field::RawBitStringCommon
        {
            /// @brief Name of the @ref cc_x509::field::CertificateMembers::ValueMembers::SignatureValue field.
            static const char* name()
            {
                return "signatureValue";
            }
        };
    };

    /// @brief Common types and functions for
    ///     @ref cc_x509::field::CertificateMembers::Value field.
    struct ValueCommon
    {
        /// @brief Name of the @ref cc_x509::field::CertificateMembers::Value field.
        static const char* name()
        {
            return "Value";
        }
    };
};

/// @brief Common types and functions for
///     @ref cc_x509::field::Certificate field.
struct CertificateCommon
{
    /// @brief Name of the @ref cc_x509::field::Certificate field.
    static const char* name()
    {
        return "Certificate";
    }
};

} // namespace field

} // namespace cc_x509
