// Generated by commsdsl2comms v7.0.0

/// @file
/// @brief Contains definition of <b>"Extension"</b> field.

#pragma once

#include <cstdint>
#include <tuple>
#include "cc_x509/asn1/der/field/BooleanDefaultFalse.h"
#include "cc_x509/asn1/der/field/Length.h"
#include "cc_x509/asn1/der/field/ObjectIdentifier.h"
#include "cc_x509/asn1/der/field/OctetString.h"
#include "cc_x509/field/ExtensionCommon.h"
#include "cc_x509/field/FieldBase.h"
#include "cc_x509/options/DefaultOptions.h"
#include "comms/field/Bundle.h"
#include "comms/field/IntValue.h"
#include "comms/options.h"

namespace cc_x509
{

namespace field
{

/// @brief Scope for all the member fields of
///     @ref Extension field.
/// @tparam TOpt Protocol options.
template <typename TOpt = cc_x509::options::DefaultOptions>
struct ExtensionMembers
{
    /// @brief Definition of <b>"Tag"</b> field.
    class Tag : public
        comms::field::IntValue<
            cc_x509::field::FieldBase<>,
            std::uint8_t,
            comms::option::def::HasName,
            comms::option::def::FailOnInvalid<>,
            comms::option::def::FixedValue,
            comms::option::def::DefaultNumValue<48>,
            comms::option::def::ValidNumValue<48>
        >
    {
        using Base =
            comms::field::IntValue<
                cc_x509::field::FieldBase<>,
                std::uint8_t,
                comms::option::def::HasName,
                comms::option::def::FailOnInvalid<>,
                comms::option::def::FixedValue,
                comms::option::def::DefaultNumValue<48>,
                comms::option::def::ValidNumValue<48>
            >;
    public:
        /// @brief Re-definition of the value type.
        using ValueType = typename Base::ValueType;

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return cc_x509::field::ExtensionMembersCommon::TagCommon::hasSpecials();
        }

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_x509::field::ExtensionMembersCommon::TagCommon::name();
        }
    };

    /// @brief Definition of <b>"Length"</b> field.
    using Length =
        cc_x509::asn1::der::field::Length<
            TOpt,
            comms::option::def::HasName
        >;

    /// @brief Scope for all the member fields of
    ///     @ref Value field.
    struct ValueMembers
    {
        /// @brief Definition of <b>"extnID"</b> field.
        class ExtnID : public
            cc_x509::asn1::der::field::ObjectIdentifier<
                TOpt,
                comms::option::def::HasName
            >
        {
            using Base =
                cc_x509::asn1::der::field::ObjectIdentifier<
                    TOpt,
                    comms::option::def::HasName
                >;
        public:
            /// @brief Name of the field.
            static const char* name()
            {
                return cc_x509::field::ExtensionMembersCommon::ValueMembersCommon::ExtnIDCommon::name();
            }
        };

        /// @brief Definition of <b>"critical"</b> field.
        class Critical : public
            cc_x509::asn1::der::field::BooleanDefaultFalse<
                TOpt,
                comms::option::def::HasName
            >
        {
            using Base =
                cc_x509::asn1::der::field::BooleanDefaultFalse<
                    TOpt,
                    comms::option::def::HasName
                >;
        public:
            /// @brief Name of the field.
            static const char* name()
            {
                return cc_x509::field::ExtensionMembersCommon::ValueMembersCommon::CriticalCommon::name();
            }
        };

        /// @brief Definition of <b>"extnValue"</b> field.
        class ExtnValue : public
            cc_x509::asn1::der::field::OctetString<
                TOpt,
                comms::option::def::HasName
            >
        {
            using Base =
                cc_x509::asn1::der::field::OctetString<
                    TOpt,
                    comms::option::def::HasName
                >;
        public:
            /// @brief Name of the field.
            static const char* name()
            {
                return cc_x509::field::ExtensionMembersCommon::ValueMembersCommon::ExtnValueCommon::name();
            }
        };

        /// @brief All members bundled in @b std::tuple.
        using All =
            std::tuple<
               ExtnID,
               Critical,
               ExtnValue
            >;
    };

    /// @brief Definition of <b>"Value"</b> field.
    class Value : public
        comms::field::Bundle<
            cc_x509::field::FieldBase<>,
            typename ValueMembers::All,
            comms::option::def::HasName,
            comms::option::def::HasVersionDependentMembers<false>
        >
    {
        using Base =
            comms::field::Bundle<
                cc_x509::field::FieldBase<>,
                typename ValueMembers::All,
                comms::option::def::HasName,
                comms::option::def::HasVersionDependentMembers<false>
            >;
    public:
        /// @brief Allow access to internal fields.
        /// @details See definition of @b COMMS_FIELD_MEMBERS_NAMES macro
        ///     related to @b comms::field::Bundle class from COMMS library
        ///     for details.
        ///
        ///     The generated values, types and access functions are:
        ///     @li @b FieldIdx_extnID index, @b Field_extnID type and @b field_extnID() access function -
        ///         for cc_x509::field::ExtensionMembers::ValueMembers::ExtnID member field.
        ///     @li @b FieldIdx_critical index, @b Field_critical type and @b field_critical() access function -
        ///         for cc_x509::field::ExtensionMembers::ValueMembers::Critical member field.
        ///     @li @b FieldIdx_extnValue index, @b Field_extnValue type and @b field_extnValue() access function -
        ///         for cc_x509::field::ExtensionMembers::ValueMembers::ExtnValue member field.
        COMMS_FIELD_MEMBERS_NAMES(
            extnID,
            critical,
            extnValue
        );

        /// @brief Name of the field.
        static const char* name()
        {
            return cc_x509::field::ExtensionMembersCommon::ValueCommon::name();
        }
    };

    /// @brief All members bundled in @b std::tuple.
    using All =
        std::tuple<
           Tag,
           Length,
           Value
        >;
};

/// @brief Definition of <b>"Extension"</b> field.
/// @tparam TOpt Protocol options.
/// @tparam TExtraOpts Extra options.
template <typename TOpt = cc_x509::options::DefaultOptions, typename... TExtraOpts>
class Extension : public
    comms::field::Bundle<
        cc_x509::field::FieldBase<>,
        typename ExtensionMembers<TOpt>::All,
        TExtraOpts...,
        comms::option::def::HasName,
        comms::option::def::RemLengthMemberField<1U>,
        comms::option::def::HasVersionDependentMembers<false>
    >
{
    using Base =
        comms::field::Bundle<
            cc_x509::field::FieldBase<>,
            typename ExtensionMembers<TOpt>::All,
            TExtraOpts...,
            comms::option::def::HasName,
            comms::option::def::RemLengthMemberField<1U>,
            comms::option::def::HasVersionDependentMembers<false>
        >;
public:
    /// @brief Allow access to internal fields.
    /// @details See definition of @b COMMS_FIELD_MEMBERS_NAMES macro
    ///     related to @b comms::field::Bundle class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and access functions are:
    ///     @li @b FieldIdx_tag index, @b Field_tag type and @b field_tag() access function -
    ///         for cc_x509::field::ExtensionMembers::Tag member field.
    ///     @li @b FieldIdx_length index, @b Field_length type and @b field_length() access function -
    ///         for cc_x509::field::ExtensionMembers::Length member field.
    ///     @li @b FieldIdx_value index, @b Field_value type and @b field_value() access function -
    ///         for cc_x509::field::ExtensionMembers::Value member field.
    COMMS_FIELD_MEMBERS_NAMES(
        tag,
        length,
        value
    );

    /// @brief Name of the field.
    static const char* name()
    {
        return cc_x509::field::ExtensionCommon::name();
    }
};

} // namespace field

} // namespace cc_x509
