// Generated by commsdsl2comms v5.1.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_x509::field::Validity field.

#pragma once

#include <cstdint>
#include "cc_x509/asn1/der/field/LengthCommon.h"
#include "cc_x509/field/TimeCommon.h"

namespace cc_x509
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref cc_x509::field::Validity field.
struct ValidityMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_x509::field::ValidityMembers::Tag field.
    struct TagCommon
    {
        /// @brief Re-definition of the value type used by
        ///     cc_x509::field::ValidityMembers::Tag field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref cc_x509::field::ValidityMembers::Tag field.
        static const char* name()
        {
            return "Tag";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref cc_x509::field::ValidityMembers::Length field.
    using LengthMembersCommon = cc_x509::asn1::der::field::LengthMembersCommon;

    /// @brief Common types and functions for
    ///     @ref cc_x509::field::ValidityMembers::Length field.
    using LengthCommon = cc_x509::asn1::der::field::LengthCommon;

    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref cc_x509::field::ValidityMembers::Value field.
    struct ValueMembersCommon
    {
        /// @brief Common definitions of the member fields of
        ///     @ref cc_x509::field::ValidityMembers::ValueMembers::NotBefore field.
        using NotBeforeMembersCommon = cc_x509::field::TimeMembersCommon;

        /// @brief Common types and functions for
        ///     @ref cc_x509::field::ValidityMembers::ValueMembers::NotBefore field.
        struct NotBeforeCommon : public cc_x509::field::TimeCommon
        {
            /// @brief Name of the @ref cc_x509::field::ValidityMembers::ValueMembers::NotBefore field.
            static const char* name()
            {
                return "notBefore";
            }
        };

        /// @brief Common definitions of the member fields of
        ///     @ref cc_x509::field::ValidityMembers::ValueMembers::NotAfter field.
        using NotAfterMembersCommon = cc_x509::field::TimeMembersCommon;

        /// @brief Common types and functions for
        ///     @ref cc_x509::field::ValidityMembers::ValueMembers::NotAfter field.
        struct NotAfterCommon : public cc_x509::field::TimeCommon
        {
            /// @brief Name of the @ref cc_x509::field::ValidityMembers::ValueMembers::NotAfter field.
            static const char* name()
            {
                return "notAfter";
            }
        };
    };

    /// @brief Common types and functions for
    ///     @ref cc_x509::field::ValidityMembers::Value field.
    struct ValueCommon
    {
        /// @brief Name of the @ref cc_x509::field::ValidityMembers::Value field.
        static const char* name()
        {
            return "Value";
        }
    };
};

/// @brief Common types and functions for
///     @ref cc_x509::field::Validity field.
struct ValidityCommon
{
    /// @brief Name of the @ref cc_x509::field::Validity field.
    static const char* name()
    {
        return "Validity";
    }
};

} // namespace field

} // namespace cc_x509
