// Generated by commsdsl2comms v7.3.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_x509::message::Msg message and its fields.

#pragma once

#include "cc_x509/field/CertificateCommon.h"

namespace cc_x509
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_x509::message::Msg message.
/// @see cc_x509::message::MsgFields
struct MsgFieldsCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref cc_x509::message::MsgFields::Certificate field.
    using CertificateMembersCommon = cc_x509::field::CertificateMembersCommon;

    /// @brief Common types and functions for
    ///     @ref cc_x509::message::MsgFields::Certificate field.
    using CertificateCommon = cc_x509::field::CertificateCommon;
};

/// @brief Common types and functions of 
///     @ref cc_x509::message::Msg message.
struct MsgCommon
{
    /// @brief Name of the @ref cc_x509::message::Msg message.
    static const char* name()
    {
        return "Message";
    }
};

} // namespace message

} // namespace cc_x509
